export const restaurantsList = [
  {
    id: 0,
    feature: "discount",
    imgUrl: "https://res.cloudinary.com/di9oiqvom/image/upload/v1689178915/DeliveryApp/Meals_zmcwwy.jpg",
    title: "Del Rey",
    rating: 5.0,
    genre: "Brazilian",
    address: "456 Elm St",
    short_description: "A fantastic Brazilian Food Experience",
    long: 40,
    lat: 50,
    dishes: [
      {
        id: 0,
        name: "Feijoada",
        short_description: "Delicious pork feijoada, Brazilian style, with rice, farofa and colve. Serves 2 people.",
        price: 45,
        image: ""
      },
      {
        id: 1,
        name: "Picanha",
        short_description: "Grilled picanha steak served with chimichurri sauce, fries, and salad.",
        price: 55,
        image: ""
      },
      {
        id: 2,
        name: "Coxinha",
        short_description: "Deep-fried chicken croquettes filled with seasoned shredded chicken.",
        price: 12,
        image: ""
      },
      {
        id: 3,
        name: "Moqueca",
        short_description: "Traditional Brazilian seafood stew with coconut milk, tomatoes, and peppers.",
        price: 35,
        image: ""
      },
      {
        id: 4,
        name: "Pastel",
        short_description: "Crispy fried pastry filled with various savory fillings like cheese, meat, or shrimp.",
        price: 8,
        image: ""
      },
      {
        id: 5,
        name: "Açaí Bowl",
        short_description: "Refreshing açaí berry smoothie bowl topped with granola, fruits, and honey.",
        price: 15,
        image: ""
      },
      {
        id: 6,
        name: "Cachaça Cocktail",
        short_description: "Classic Brazilian cocktail made with cachaça, lime, and sugar.",
        price: 10,
        image: ""
      },
      {
        id: 7,
        name: "Brigadeiro",
        short_description: "Traditional Brazilian chocolate truffles made with condensed milk and cocoa powder.",
        price: 6,
        image: ""
      },
    ],
  },
  {
    id: 1,
    feature: "discount",
    imgUrl: "https://res.cloudinary.com/di9oiqvom/image/upload/v1689180290/DeliveryApp/Restaurants/Leve-Pizzaria_qbk9zg.jpg",
    title: "Leve Pizza",
    rating: 4.2,
    genre: "Italian",
    address: "789 Oak St",
    short_description: "Delicious pizzas made with love",
    long: 60,
    lat: 70,
    dishes: [],
  },
  {
    id: 2,
    feature: "discount",
    imgUrl: "https://res.cloudinary.com/di9oiqvom/image/upload/v1689180290/DeliveryApp/Restaurants/OAK-BERRY_ud4snk.jpg",
    title: "OAK BERRY",
    rating: 4.7,
    genre: "Healthy",
    address: "321 Pine St",
    short_description: "Fresh and nutritious bowls and smoothies",
    long: 80,
    lat: 90,
    dishes: [],
  },
  {
    id: 3,
    feature: "Sponsored",
    imgUrl: "https://res.cloudinary.com/di9oiqvom/image/upload/v1689183186/DeliveryApp/Restaurants/MC_qcrbux.jpg",
    title: "Mc Donalds",
    rating: 4.8,
    genre: "Fast-Food",
    address: "987 Maple St",
    short_description: "The iconic fast-food chain serving up delicious burgers, fries, and smiles",
    long: 100,
    lat: 110,
    dishes: [],
  },
  {
    id: 4,
    feature: "Sponsored",
    imgUrl: "https://res.cloudinary.com/di9oiqvom/image/upload/v1689183185/DeliveryApp/Restaurants/KFC_ywand4.jpg",
    title: "KFC",
    rating: 4.7,
    genre: "Fast-Food",
    address: "654 Birch St",
    short_description: "The iconic fast-food chain serving up delicious burgers, fries, and smiles",
    long: 120,
    lat: 130,
    dishes: [],
  },
  {
    id: 5,
    feature: "Sponsored",
    imgUrl: "https://res.cloudinary.com/di9oiqvom/image/upload/v1689180710/DeliveryApp/Restaurants/Mister-Burguer_hsrwfy.jpg",
    title: "Mister Burguer",
    rating: 4.6,
    genre: "Burgers",
    address: "321 Oak St",
    short_description: "Juicy and flavorful burgers for everyone",
    long: 140,
    lat: 150,
    dishes: [],
  },
  {
    id: 6,
    feature: "near",
    imgUrl: "https://res.cloudinary.com/di9oiqvom/image/upload/v1689180290/DeliveryApp/Restaurants/Indian-Way_rei4nc.jpg",
    title: "Indian Way",
    rating: 4.4,
    genre: "Indian",
    address: "987 Pine St",
    short_description: "Spicy and aromatic Indian dishes",
    long: 160,
    lat: 170,
    dishes: [],
  },
  {
    id: 7,
    feature: "near",
    imgUrl: "https://res.cloudinary.com/di9oiqvom/image/upload/v1689180290/DeliveryApp/Restaurants/So-Casquinha_kkj6ig.jpg",
    title: "So Casquinha",
    rating: 4.1,
    genre: "Brazilian",
    address: "654 Elm St",
    short_description: "Delightful Brazilian street food",
    long: 180,
    lat: 190,
    dishes: [],
  },
  {
    id: 8,
    feature: "near",
    imgUrl: "https://res.cloudinary.com/di9oiqvom/image/upload/v1689180710/DeliveryApp/Restaurants/We-Love-Burguers_frttgd.jpg",
    title: "We-Love-Burgers",
    rating: 4.9,
    genre: "Burgers",
    address: "321 Pine St",
    short_description: "Gourmet burgers made with passion",
    long: 200,
    lat: 210,
    dishes: [],
  },
  {
    id: 9,
    feature: "Sponsored",
    imgUrl: "https://res.cloudinary.com/di9oiqvom/image/upload/v1689180290/DeliveryApp/Restaurants/MatsuSushi_hll9l6.jpg",
    title: "Matsu Sushi",
    rating: 4.8,
    genre: "Japanese",
    address: "987 Maple St",
    short_description: "Authentic sushi made with the finest ingredients",
    long: 100,
    lat: 110,
    dishes: [],
  },
  {
    id: 10,
    feature: "Sponsored",
    imgUrl: "https://res.cloudinary.com/di9oiqvom/image/upload/v1689180290/DeliveryApp/Restaurants/No-Rise-Pizza_kjsn3y.jpg",
    title: "No-Rise Pizza",
    rating: 4.3,
    genre: "Italian",
    address: "654 Birch St",
    short_description: "Delicious and fluffy pizza crusts",
    long: 120,
    lat: 130,
    dishes: [],
  },
  {
    id: 11,
    feature: "discount",
    imgUrl: "https://res.cloudinary.com/di9oiqvom/image/upload/v1689180290/DeliveryApp/Restaurants/YoSushi_ar8aha.jpg",
    title: "Yo! Sushi",
    rating: 5.0,
    genre: "Japanese",
    address: "456 Elm St",
    short_description: "A fantastic sushi experience",
    long: 40,
    lat: 50,
    dishes: [],
  },
];
